# Generated by Django 3.2.7 on 2021-09-15 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Электроная почта')),
                ('username', models.CharField(max_length=64, verbose_name='Ник')),
                ('firstname', models.CharField(max_length=64, verbose_name='Имя')),
                ('lastname', models.CharField(max_length=64, verbose_name='Фамилия')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
